name: Run tests

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "README.md"

env:
  CARGO_TERM_COLOR: always

jobs:
  check-rust-compat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_version: ["1.75", "1.76", "1.78"]
    steps:
      - name: rustup toolchain install ${{ matrix.rust_version }}
        run: |
          rustup toolchain install ${{ matrix.rust_version }}
      - uses: actions/checkout@v4
      - run: rustup override set ${{ matrix.rust_version }}
      - name: cargo check --workspace
        run: cargo check --workspace
  test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v1
      - name: Run tests
        run: cargo test --workspace
